[platformio]
default_envs = uno

[env:uno]
platform = atmelavr@5.1.0
board = uno
framework = arduino
monitor_speed = 115200
build_flags = -Wall -Wextra
lib_deps = winlinvip/SimpleDHT@^1.0.15

[env:uno_csv]
extends = env:uno
build_flags = -Wall -Wextra -DSENTINEL_CSV=1
