[platformio]
default_envs = uno

[env:uno]
platform = atmelavr@5.1.0
board = uno
framework = arduino
monitor_speed = 500000
build_flags = -Wall -Wextra
lib_deps = paulstoffregen/OneWire@2.3.8

[env:uno_csv]
extends = env:uno
monitor_speed = 115200
build_flags = -Wall -Wextra -DSENTINEL_CSV=1

[env:uno_edge]
extends = env:uno
build_flags = -Wall -Wextra -DSENTINEL_EDGE=1
